// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rtcmsg.proto

package com.example.webrtc;

public final class Rtcmsg {
  private Rtcmsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code OfferType}
   */
  public enum OfferType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OFFER = 1;</code>
     */
    OFFER(1),
    /**
     * <code>PRANSWER = 2;</code>
     */
    PRANSWER(2),
    /**
     * <code>ANSWER = 4;</code>
     */
    ANSWER(4),
    ;

    /**
     * <code>OFFER = 1;</code>
     */
    public static final int OFFER_VALUE = 1;
    /**
     * <code>PRANSWER = 2;</code>
     */
    public static final int PRANSWER_VALUE = 2;
    /**
     * <code>ANSWER = 4;</code>
     */
    public static final int ANSWER_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OfferType valueOf(int value) {
      return forNumber(value);
    }

    public static OfferType forNumber(int value) {
      switch (value) {
        case 1: return OFFER;
        case 2: return PRANSWER;
        case 4: return ANSWER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OfferType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OfferType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OfferType>() {
            public OfferType findValueByNumber(int number) {
              return OfferType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.webrtc.Rtcmsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final OfferType[] VALUES = values();

    public static OfferType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OfferType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OfferType)
  }

  public interface IceCandidateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IceCandidate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sdp_mid = 1;</code>
     */
    boolean hasSdpMid();
    /**
     * <code>required string sdp_mid = 1;</code>
     */
    java.lang.String getSdpMid();
    /**
     * <code>required string sdp_mid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdpMidBytes();

    /**
     * <code>required int32 sdp_m_line_index = 2;</code>
     */
    boolean hasSdpMLineIndex();
    /**
     * <code>required int32 sdp_m_line_index = 2;</code>
     */
    int getSdpMLineIndex();

    /**
     * <code>required string sdp = 3;</code>
     */
    boolean hasSdp();
    /**
     * <code>required string sdp = 3;</code>
     */
    java.lang.String getSdp();
    /**
     * <code>required string sdp = 3;</code>
     */
    com.google.protobuf.ByteString
        getSdpBytes();

    /**
     * <code>required string serverUrl = 4;</code>
     */
    boolean hasServerUrl();
    /**
     * <code>required string serverUrl = 4;</code>
     */
    java.lang.String getServerUrl();
    /**
     * <code>required string serverUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerUrlBytes();
  }
  /**
   * Protobuf type {@code IceCandidate}
   */
  public  static final class IceCandidate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IceCandidate)
      IceCandidateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IceCandidate.newBuilder() to construct.
    private IceCandidate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IceCandidate() {
      sdpMid_ = "";
      sdp_ = "";
      serverUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IceCandidate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sdpMid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sdpMLineIndex_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              sdp_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              serverUrl_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.webrtc.Rtcmsg.internal_static_IceCandidate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.webrtc.Rtcmsg.internal_static_IceCandidate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.webrtc.Rtcmsg.IceCandidate.class, com.example.webrtc.Rtcmsg.IceCandidate.Builder.class);
    }

    private int bitField0_;
    public static final int SDP_MID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sdpMid_;
    /**
     * <code>required string sdp_mid = 1;</code>
     */
    public boolean hasSdpMid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string sdp_mid = 1;</code>
     */
    public java.lang.String getSdpMid() {
      java.lang.Object ref = sdpMid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdpMid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sdp_mid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdpMidBytes() {
      java.lang.Object ref = sdpMid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdpMid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDP_M_LINE_INDEX_FIELD_NUMBER = 2;
    private int sdpMLineIndex_;
    /**
     * <code>required int32 sdp_m_line_index = 2;</code>
     */
    public boolean hasSdpMLineIndex() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 sdp_m_line_index = 2;</code>
     */
    public int getSdpMLineIndex() {
      return sdpMLineIndex_;
    }

    public static final int SDP_FIELD_NUMBER = 3;
    private volatile java.lang.Object sdp_;
    /**
     * <code>required string sdp = 3;</code>
     */
    public boolean hasSdp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string sdp = 3;</code>
     */
    public java.lang.String getSdp() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sdp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSdpBytes() {
      java.lang.Object ref = sdp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object serverUrl_;
    /**
     * <code>required string serverUrl = 4;</code>
     */
    public boolean hasServerUrl() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string serverUrl = 4;</code>
     */
    public java.lang.String getServerUrl() {
      java.lang.Object ref = serverUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerUrlBytes() {
      java.lang.Object ref = serverUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSdpMid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSdpMLineIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSdp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sdpMid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, sdpMLineIndex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sdp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serverUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sdpMid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sdpMLineIndex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sdp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serverUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.webrtc.Rtcmsg.IceCandidate)) {
        return super.equals(obj);
      }
      com.example.webrtc.Rtcmsg.IceCandidate other = (com.example.webrtc.Rtcmsg.IceCandidate) obj;

      if (hasSdpMid() != other.hasSdpMid()) return false;
      if (hasSdpMid()) {
        if (!getSdpMid()
            .equals(other.getSdpMid())) return false;
      }
      if (hasSdpMLineIndex() != other.hasSdpMLineIndex()) return false;
      if (hasSdpMLineIndex()) {
        if (getSdpMLineIndex()
            != other.getSdpMLineIndex()) return false;
      }
      if (hasSdp() != other.hasSdp()) return false;
      if (hasSdp()) {
        if (!getSdp()
            .equals(other.getSdp())) return false;
      }
      if (hasServerUrl() != other.hasServerUrl()) return false;
      if (hasServerUrl()) {
        if (!getServerUrl()
            .equals(other.getServerUrl())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSdpMid()) {
        hash = (37 * hash) + SDP_MID_FIELD_NUMBER;
        hash = (53 * hash) + getSdpMid().hashCode();
      }
      if (hasSdpMLineIndex()) {
        hash = (37 * hash) + SDP_M_LINE_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getSdpMLineIndex();
      }
      if (hasSdp()) {
        hash = (37 * hash) + SDP_FIELD_NUMBER;
        hash = (53 * hash) + getSdp().hashCode();
      }
      if (hasServerUrl()) {
        hash = (37 * hash) + SERVERURL_FIELD_NUMBER;
        hash = (53 * hash) + getServerUrl().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.IceCandidate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.webrtc.Rtcmsg.IceCandidate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IceCandidate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IceCandidate)
        com.example.webrtc.Rtcmsg.IceCandidateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.webrtc.Rtcmsg.internal_static_IceCandidate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.webrtc.Rtcmsg.internal_static_IceCandidate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.webrtc.Rtcmsg.IceCandidate.class, com.example.webrtc.Rtcmsg.IceCandidate.Builder.class);
      }

      // Construct using com.example.webrtc.Rtcmsg.IceCandidate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sdpMid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sdpMLineIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sdp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        serverUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.webrtc.Rtcmsg.internal_static_IceCandidate_descriptor;
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.IceCandidate getDefaultInstanceForType() {
        return com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.IceCandidate build() {
        com.example.webrtc.Rtcmsg.IceCandidate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.IceCandidate buildPartial() {
        com.example.webrtc.Rtcmsg.IceCandidate result = new com.example.webrtc.Rtcmsg.IceCandidate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sdpMid_ = sdpMid_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sdpMLineIndex_ = sdpMLineIndex_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sdp_ = sdp_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverUrl_ = serverUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.webrtc.Rtcmsg.IceCandidate) {
          return mergeFrom((com.example.webrtc.Rtcmsg.IceCandidate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.webrtc.Rtcmsg.IceCandidate other) {
        if (other == com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance()) return this;
        if (other.hasSdpMid()) {
          bitField0_ |= 0x00000001;
          sdpMid_ = other.sdpMid_;
          onChanged();
        }
        if (other.hasSdpMLineIndex()) {
          setSdpMLineIndex(other.getSdpMLineIndex());
        }
        if (other.hasSdp()) {
          bitField0_ |= 0x00000004;
          sdp_ = other.sdp_;
          onChanged();
        }
        if (other.hasServerUrl()) {
          bitField0_ |= 0x00000008;
          serverUrl_ = other.serverUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSdpMid()) {
          return false;
        }
        if (!hasSdpMLineIndex()) {
          return false;
        }
        if (!hasSdp()) {
          return false;
        }
        if (!hasServerUrl()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.webrtc.Rtcmsg.IceCandidate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.webrtc.Rtcmsg.IceCandidate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sdpMid_ = "";
      /**
       * <code>required string sdp_mid = 1;</code>
       */
      public boolean hasSdpMid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string sdp_mid = 1;</code>
       */
      public java.lang.String getSdpMid() {
        java.lang.Object ref = sdpMid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdpMid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sdp_mid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdpMidBytes() {
        java.lang.Object ref = sdpMid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdpMid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sdp_mid = 1;</code>
       */
      public Builder setSdpMid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdpMid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sdp_mid = 1;</code>
       */
      public Builder clearSdpMid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sdpMid_ = getDefaultInstance().getSdpMid();
        onChanged();
        return this;
      }
      /**
       * <code>required string sdp_mid = 1;</code>
       */
      public Builder setSdpMidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sdpMid_ = value;
        onChanged();
        return this;
      }

      private int sdpMLineIndex_ ;
      /**
       * <code>required int32 sdp_m_line_index = 2;</code>
       */
      public boolean hasSdpMLineIndex() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 sdp_m_line_index = 2;</code>
       */
      public int getSdpMLineIndex() {
        return sdpMLineIndex_;
      }
      /**
       * <code>required int32 sdp_m_line_index = 2;</code>
       */
      public Builder setSdpMLineIndex(int value) {
        bitField0_ |= 0x00000002;
        sdpMLineIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sdp_m_line_index = 2;</code>
       */
      public Builder clearSdpMLineIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sdpMLineIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sdp_ = "";
      /**
       * <code>required string sdp = 3;</code>
       */
      public boolean hasSdp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string sdp = 3;</code>
       */
      public java.lang.String getSdp() {
        java.lang.Object ref = sdp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sdp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSdpBytes() {
        java.lang.Object ref = sdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sdp = 3;</code>
       */
      public Builder setSdp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sdp = 3;</code>
       */
      public Builder clearSdp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sdp_ = getDefaultInstance().getSdp();
        onChanged();
        return this;
      }
      /**
       * <code>required string sdp = 3;</code>
       */
      public Builder setSdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sdp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverUrl_ = "";
      /**
       * <code>required string serverUrl = 4;</code>
       */
      public boolean hasServerUrl() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string serverUrl = 4;</code>
       */
      public java.lang.String getServerUrl() {
        java.lang.Object ref = serverUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerUrlBytes() {
        java.lang.Object ref = serverUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverUrl = 4;</code>
       */
      public Builder setServerUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverUrl = 4;</code>
       */
      public Builder clearServerUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverUrl_ = getDefaultInstance().getServerUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverUrl = 4;</code>
       */
      public Builder setServerUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IceCandidate)
    }

    // @@protoc_insertion_point(class_scope:IceCandidate)
    private static final com.example.webrtc.Rtcmsg.IceCandidate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.webrtc.Rtcmsg.IceCandidate();
    }

    public static com.example.webrtc.Rtcmsg.IceCandidate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IceCandidate>
        PARSER = new com.google.protobuf.AbstractParser<IceCandidate>() {
      @java.lang.Override
      public IceCandidate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IceCandidate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IceCandidate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IceCandidate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.webrtc.Rtcmsg.IceCandidate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SessionDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string offer_type = 1;</code>
     */
    boolean hasOfferType();
    /**
     * <code>required string offer_type = 1;</code>
     */
    java.lang.String getOfferType();
    /**
     * <code>required string offer_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getOfferTypeBytes();

    /**
     * <code>required string desc = 2;</code>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 2;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>required string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code SessionDescription}
   */
  public  static final class SessionDescription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SessionDescription)
      SessionDescriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SessionDescription.newBuilder() to construct.
    private SessionDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SessionDescription() {
      offerType_ = "";
      desc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SessionDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              offerType_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              desc_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.webrtc.Rtcmsg.internal_static_SessionDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.webrtc.Rtcmsg.internal_static_SessionDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.webrtc.Rtcmsg.SessionDescription.class, com.example.webrtc.Rtcmsg.SessionDescription.Builder.class);
    }

    private int bitField0_;
    public static final int OFFER_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object offerType_;
    /**
     * <code>required string offer_type = 1;</code>
     */
    public boolean hasOfferType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string offer_type = 1;</code>
     */
    public java.lang.String getOfferType() {
      java.lang.Object ref = offerType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          offerType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string offer_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOfferTypeBytes() {
      java.lang.Object ref = offerType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        offerType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object desc_;
    /**
     * <code>required string desc = 2;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string desc = 2;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOfferType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, offerType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, offerType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.webrtc.Rtcmsg.SessionDescription)) {
        return super.equals(obj);
      }
      com.example.webrtc.Rtcmsg.SessionDescription other = (com.example.webrtc.Rtcmsg.SessionDescription) obj;

      if (hasOfferType() != other.hasOfferType()) return false;
      if (hasOfferType()) {
        if (!getOfferType()
            .equals(other.getOfferType())) return false;
      }
      if (hasDesc() != other.hasDesc()) return false;
      if (hasDesc()) {
        if (!getDesc()
            .equals(other.getDesc())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOfferType()) {
        hash = (37 * hash) + OFFER_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getOfferType().hashCode();
      }
      if (hasDesc()) {
        hash = (37 * hash) + DESC_FIELD_NUMBER;
        hash = (53 * hash) + getDesc().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.SessionDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.webrtc.Rtcmsg.SessionDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SessionDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionDescription)
        com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.webrtc.Rtcmsg.internal_static_SessionDescription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.webrtc.Rtcmsg.internal_static_SessionDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.webrtc.Rtcmsg.SessionDescription.class, com.example.webrtc.Rtcmsg.SessionDescription.Builder.class);
      }

      // Construct using com.example.webrtc.Rtcmsg.SessionDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        offerType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.webrtc.Rtcmsg.internal_static_SessionDescription_descriptor;
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.SessionDescription getDefaultInstanceForType() {
        return com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.SessionDescription build() {
        com.example.webrtc.Rtcmsg.SessionDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.SessionDescription buildPartial() {
        com.example.webrtc.Rtcmsg.SessionDescription result = new com.example.webrtc.Rtcmsg.SessionDescription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.offerType_ = offerType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desc_ = desc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.webrtc.Rtcmsg.SessionDescription) {
          return mergeFrom((com.example.webrtc.Rtcmsg.SessionDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.webrtc.Rtcmsg.SessionDescription other) {
        if (other == com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance()) return this;
        if (other.hasOfferType()) {
          bitField0_ |= 0x00000001;
          offerType_ = other.offerType_;
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000002;
          desc_ = other.desc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOfferType()) {
          return false;
        }
        if (!hasDesc()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.webrtc.Rtcmsg.SessionDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.webrtc.Rtcmsg.SessionDescription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object offerType_ = "";
      /**
       * <code>required string offer_type = 1;</code>
       */
      public boolean hasOfferType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string offer_type = 1;</code>
       */
      public java.lang.String getOfferType() {
        java.lang.Object ref = offerType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            offerType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string offer_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOfferTypeBytes() {
        java.lang.Object ref = offerType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          offerType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string offer_type = 1;</code>
       */
      public Builder setOfferType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        offerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string offer_type = 1;</code>
       */
      public Builder clearOfferType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offerType_ = getDefaultInstance().getOfferType();
        onChanged();
        return this;
      }
      /**
       * <code>required string offer_type = 1;</code>
       */
      public Builder setOfferTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        offerType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>required string desc = 2;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            desc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SessionDescription)
    }

    // @@protoc_insertion_point(class_scope:SessionDescription)
    private static final com.example.webrtc.Rtcmsg.SessionDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.webrtc.Rtcmsg.SessionDescription();
    }

    public static com.example.webrtc.Rtcmsg.SessionDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SessionDescription>
        PARSER = new com.google.protobuf.AbstractParser<SessionDescription>() {
      @java.lang.Override
      public SessionDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionDescription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SessionDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SessionDescription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.webrtc.Rtcmsg.SessionDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ToMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ToMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .IceCandidate ice = 1;</code>
     */
    boolean hasIce();
    /**
     * <code>optional .IceCandidate ice = 1;</code>
     */
    com.example.webrtc.Rtcmsg.IceCandidate getIce();
    /**
     * <code>optional .IceCandidate ice = 1;</code>
     */
    com.example.webrtc.Rtcmsg.IceCandidateOrBuilder getIceOrBuilder();

    /**
     * <code>optional .SessionDescription sdp = 2;</code>
     */
    boolean hasSdp();
    /**
     * <code>optional .SessionDescription sdp = 2;</code>
     */
    com.example.webrtc.Rtcmsg.SessionDescription getSdp();
    /**
     * <code>optional .SessionDescription sdp = 2;</code>
     */
    com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder getSdpOrBuilder();
  }
  /**
   * Protobuf type {@code ToMessage}
   */
  public  static final class ToMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ToMessage)
      ToMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToMessage.newBuilder() to construct.
    private ToMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.webrtc.Rtcmsg.IceCandidate.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = ice_.toBuilder();
              }
              ice_ = input.readMessage(com.example.webrtc.Rtcmsg.IceCandidate.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ice_);
                ice_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.example.webrtc.Rtcmsg.SessionDescription.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = sdp_.toBuilder();
              }
              sdp_ = input.readMessage(com.example.webrtc.Rtcmsg.SessionDescription.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sdp_);
                sdp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.webrtc.Rtcmsg.internal_static_ToMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.webrtc.Rtcmsg.internal_static_ToMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.webrtc.Rtcmsg.ToMessage.class, com.example.webrtc.Rtcmsg.ToMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ICE_FIELD_NUMBER = 1;
    private com.example.webrtc.Rtcmsg.IceCandidate ice_;
    /**
     * <code>optional .IceCandidate ice = 1;</code>
     */
    public boolean hasIce() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .IceCandidate ice = 1;</code>
     */
    public com.example.webrtc.Rtcmsg.IceCandidate getIce() {
      return ice_ == null ? com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance() : ice_;
    }
    /**
     * <code>optional .IceCandidate ice = 1;</code>
     */
    public com.example.webrtc.Rtcmsg.IceCandidateOrBuilder getIceOrBuilder() {
      return ice_ == null ? com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance() : ice_;
    }

    public static final int SDP_FIELD_NUMBER = 2;
    private com.example.webrtc.Rtcmsg.SessionDescription sdp_;
    /**
     * <code>optional .SessionDescription sdp = 2;</code>
     */
    public boolean hasSdp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .SessionDescription sdp = 2;</code>
     */
    public com.example.webrtc.Rtcmsg.SessionDescription getSdp() {
      return sdp_ == null ? com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance() : sdp_;
    }
    /**
     * <code>optional .SessionDescription sdp = 2;</code>
     */
    public com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder getSdpOrBuilder() {
      return sdp_ == null ? com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance() : sdp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasIce()) {
        if (!getIce().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSdp()) {
        if (!getSdp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getIce());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getSdp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIce());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSdp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.webrtc.Rtcmsg.ToMessage)) {
        return super.equals(obj);
      }
      com.example.webrtc.Rtcmsg.ToMessage other = (com.example.webrtc.Rtcmsg.ToMessage) obj;

      if (hasIce() != other.hasIce()) return false;
      if (hasIce()) {
        if (!getIce()
            .equals(other.getIce())) return false;
      }
      if (hasSdp() != other.hasSdp()) return false;
      if (hasSdp()) {
        if (!getSdp()
            .equals(other.getSdp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIce()) {
        hash = (37 * hash) + ICE_FIELD_NUMBER;
        hash = (53 * hash) + getIce().hashCode();
      }
      if (hasSdp()) {
        hash = (37 * hash) + SDP_FIELD_NUMBER;
        hash = (53 * hash) + getSdp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.webrtc.Rtcmsg.ToMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.webrtc.Rtcmsg.ToMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ToMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ToMessage)
        com.example.webrtc.Rtcmsg.ToMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.webrtc.Rtcmsg.internal_static_ToMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.webrtc.Rtcmsg.internal_static_ToMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.webrtc.Rtcmsg.ToMessage.class, com.example.webrtc.Rtcmsg.ToMessage.Builder.class);
      }

      // Construct using com.example.webrtc.Rtcmsg.ToMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIceFieldBuilder();
          getSdpFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (iceBuilder_ == null) {
          ice_ = null;
        } else {
          iceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (sdpBuilder_ == null) {
          sdp_ = null;
        } else {
          sdpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.webrtc.Rtcmsg.internal_static_ToMessage_descriptor;
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.ToMessage getDefaultInstanceForType() {
        return com.example.webrtc.Rtcmsg.ToMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.ToMessage build() {
        com.example.webrtc.Rtcmsg.ToMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.webrtc.Rtcmsg.ToMessage buildPartial() {
        com.example.webrtc.Rtcmsg.ToMessage result = new com.example.webrtc.Rtcmsg.ToMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (iceBuilder_ == null) {
            result.ice_ = ice_;
          } else {
            result.ice_ = iceBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (sdpBuilder_ == null) {
            result.sdp_ = sdp_;
          } else {
            result.sdp_ = sdpBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.webrtc.Rtcmsg.ToMessage) {
          return mergeFrom((com.example.webrtc.Rtcmsg.ToMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.webrtc.Rtcmsg.ToMessage other) {
        if (other == com.example.webrtc.Rtcmsg.ToMessage.getDefaultInstance()) return this;
        if (other.hasIce()) {
          mergeIce(other.getIce());
        }
        if (other.hasSdp()) {
          mergeSdp(other.getSdp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasIce()) {
          if (!getIce().isInitialized()) {
            return false;
          }
        }
        if (hasSdp()) {
          if (!getSdp().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.webrtc.Rtcmsg.ToMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.webrtc.Rtcmsg.ToMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.example.webrtc.Rtcmsg.IceCandidate ice_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.webrtc.Rtcmsg.IceCandidate, com.example.webrtc.Rtcmsg.IceCandidate.Builder, com.example.webrtc.Rtcmsg.IceCandidateOrBuilder> iceBuilder_;
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public boolean hasIce() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public com.example.webrtc.Rtcmsg.IceCandidate getIce() {
        if (iceBuilder_ == null) {
          return ice_ == null ? com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance() : ice_;
        } else {
          return iceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public Builder setIce(com.example.webrtc.Rtcmsg.IceCandidate value) {
        if (iceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ice_ = value;
          onChanged();
        } else {
          iceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public Builder setIce(
          com.example.webrtc.Rtcmsg.IceCandidate.Builder builderForValue) {
        if (iceBuilder_ == null) {
          ice_ = builderForValue.build();
          onChanged();
        } else {
          iceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public Builder mergeIce(com.example.webrtc.Rtcmsg.IceCandidate value) {
        if (iceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              ice_ != null &&
              ice_ != com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance()) {
            ice_ =
              com.example.webrtc.Rtcmsg.IceCandidate.newBuilder(ice_).mergeFrom(value).buildPartial();
          } else {
            ice_ = value;
          }
          onChanged();
        } else {
          iceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public Builder clearIce() {
        if (iceBuilder_ == null) {
          ice_ = null;
          onChanged();
        } else {
          iceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public com.example.webrtc.Rtcmsg.IceCandidate.Builder getIceBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      public com.example.webrtc.Rtcmsg.IceCandidateOrBuilder getIceOrBuilder() {
        if (iceBuilder_ != null) {
          return iceBuilder_.getMessageOrBuilder();
        } else {
          return ice_ == null ?
              com.example.webrtc.Rtcmsg.IceCandidate.getDefaultInstance() : ice_;
        }
      }
      /**
       * <code>optional .IceCandidate ice = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.webrtc.Rtcmsg.IceCandidate, com.example.webrtc.Rtcmsg.IceCandidate.Builder, com.example.webrtc.Rtcmsg.IceCandidateOrBuilder> 
          getIceFieldBuilder() {
        if (iceBuilder_ == null) {
          iceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.webrtc.Rtcmsg.IceCandidate, com.example.webrtc.Rtcmsg.IceCandidate.Builder, com.example.webrtc.Rtcmsg.IceCandidateOrBuilder>(
                  getIce(),
                  getParentForChildren(),
                  isClean());
          ice_ = null;
        }
        return iceBuilder_;
      }

      private com.example.webrtc.Rtcmsg.SessionDescription sdp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.webrtc.Rtcmsg.SessionDescription, com.example.webrtc.Rtcmsg.SessionDescription.Builder, com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder> sdpBuilder_;
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public boolean hasSdp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public com.example.webrtc.Rtcmsg.SessionDescription getSdp() {
        if (sdpBuilder_ == null) {
          return sdp_ == null ? com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance() : sdp_;
        } else {
          return sdpBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public Builder setSdp(com.example.webrtc.Rtcmsg.SessionDescription value) {
        if (sdpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sdp_ = value;
          onChanged();
        } else {
          sdpBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public Builder setSdp(
          com.example.webrtc.Rtcmsg.SessionDescription.Builder builderForValue) {
        if (sdpBuilder_ == null) {
          sdp_ = builderForValue.build();
          onChanged();
        } else {
          sdpBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public Builder mergeSdp(com.example.webrtc.Rtcmsg.SessionDescription value) {
        if (sdpBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              sdp_ != null &&
              sdp_ != com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance()) {
            sdp_ =
              com.example.webrtc.Rtcmsg.SessionDescription.newBuilder(sdp_).mergeFrom(value).buildPartial();
          } else {
            sdp_ = value;
          }
          onChanged();
        } else {
          sdpBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public Builder clearSdp() {
        if (sdpBuilder_ == null) {
          sdp_ = null;
          onChanged();
        } else {
          sdpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public com.example.webrtc.Rtcmsg.SessionDescription.Builder getSdpBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSdpFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      public com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder getSdpOrBuilder() {
        if (sdpBuilder_ != null) {
          return sdpBuilder_.getMessageOrBuilder();
        } else {
          return sdp_ == null ?
              com.example.webrtc.Rtcmsg.SessionDescription.getDefaultInstance() : sdp_;
        }
      }
      /**
       * <code>optional .SessionDescription sdp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.webrtc.Rtcmsg.SessionDescription, com.example.webrtc.Rtcmsg.SessionDescription.Builder, com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder> 
          getSdpFieldBuilder() {
        if (sdpBuilder_ == null) {
          sdpBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.webrtc.Rtcmsg.SessionDescription, com.example.webrtc.Rtcmsg.SessionDescription.Builder, com.example.webrtc.Rtcmsg.SessionDescriptionOrBuilder>(
                  getSdp(),
                  getParentForChildren(),
                  isClean());
          sdp_ = null;
        }
        return sdpBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ToMessage)
    }

    // @@protoc_insertion_point(class_scope:ToMessage)
    private static final com.example.webrtc.Rtcmsg.ToMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.webrtc.Rtcmsg.ToMessage();
    }

    public static com.example.webrtc.Rtcmsg.ToMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ToMessage>
        PARSER = new com.google.protobuf.AbstractParser<ToMessage>() {
      @java.lang.Override
      public ToMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.webrtc.Rtcmsg.ToMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IceCandidate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IceCandidate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SessionDescription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SessionDescription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ToMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ToMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014rtcmsg.proto\"Y\n\014IceCandidate\022\017\n\007sdp_mi" +
      "d\030\001 \002(\t\022\030\n\020sdp_m_line_index\030\002 \002(\005\022\013\n\003sdp" +
      "\030\003 \002(\t\022\021\n\tserverUrl\030\004 \002(\t\"6\n\022SessionDesc" +
      "ription\022\022\n\noffer_type\030\001 \002(\t\022\014\n\004desc\030\002 \002(" +
      "\t\"I\n\tToMessage\022\032\n\003ice\030\001 \001(\0132\r.IceCandida" +
      "te\022 \n\003sdp\030\002 \001(\0132\023.SessionDescription*0\n\t" +
      "OfferType\022\t\n\005OFFER\020\001\022\014\n\010PRANSWER\020\002\022\n\n\006AN" +
      "SWER\020\004B\024\n\022com.example.webrtc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IceCandidate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IceCandidate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IceCandidate_descriptor,
        new java.lang.String[] { "SdpMid", "SdpMLineIndex", "Sdp", "ServerUrl", });
    internal_static_SessionDescription_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SessionDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SessionDescription_descriptor,
        new java.lang.String[] { "OfferType", "Desc", });
    internal_static_ToMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ToMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ToMessage_descriptor,
        new java.lang.String[] { "Ice", "Sdp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
